FROM --platform=$TARGETPLATFORM eternalfree/nginx:1.26.1

COPY ./scripts/wait-for-it.sh .

ENV NGINX_WAITHOST=localhost NGINX_WAITPORT=80

RUN chmod +x /wait-for-it.sh

ENTRYPOINT /wait-for-it.sh $NGINX_WAITHOST:$NGINX_WAITPORT --timeout=0 \
    &&  nginx -g 'daemon off;'