# escape=`

FROM hyx1229/powershell:lts-windowsservercore-ltsc2022

WORKDIR /docker

RUN powershell -command " `
Invoke-WebRequest 'https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1' `
-OutFile ./install-docker-ce.ps1; `
./install-docker-ce.ps1 -DockerVersion '24.0.2' -NoRestart; `
./install-docker-ce.ps1 -DockerVersion '24.0.2' -NoRestart;"

COPY ./docker-compose.exe .

RUN setx PATH "%PATH%;C:\docker"

