name: "buildx"
on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "build/**"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "build/**"

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ALIYUN_DOCKERHUB: ${{ vars.ALIYUN_DOCKERHUB }}
  ALIYUN_DOCKERHUB_USERNAME: ${{ vars.ALIYUN_DOCKERHUB_USERNAME }}
  ALIYUN_DOCKERHUB_TOKEN: ${{ secrets.ALIYUN_DOCKERHUB_TOKEN }}

jobs:
  # ----------------------------------- build -----------------------------------
  build-hub-windows:
    runs-on: windows-latest
    name: Images to DockerHub (Windows)
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: ./build-push.ps1 -Namespace hyx1229

  build-hub-linux:
    runs-on: ubuntu-22.04
    name: Images to DockerHub (Linux)
    needs: [build-hub-windows]
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: ./build-push.ps1 -Namespace hyx1229

  build-aliyun-windows:
    runs-on: windows-latest
    name: Images to Aliyun  (Windows)
    needs: [build-hub-linux]
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to Aliyun
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.ALIYUN_DOCKERHUB}}
          username: ${{env.ALIYUN_DOCKERHUB_USERNAME}}
          password: ${{env.ALIYUN_DOCKERHUB_TOKEN}}

      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: ./build-sync-manifest.ps1 -TargetRegistry $env:ALIYUN_DOCKERHUB

  build-aliyun-linux:
    runs-on: ubuntu-22.04
    name: Images to Aliyun (Linux)
    needs: [build-aliyun-windows]
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: ${{env.ALIYUN_DOCKERHUB}}
          username: ${{env.ALIYUN_DOCKERHUB_USERNAME}}
          password: ${{env.ALIYUN_DOCKERHUB_TOKEN}}

      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: ./build-sync-manifest.ps1 -TargetRegistry $env:ALIYUN_DOCKERHUB

  # ----------------------------------- sync -----------------------------------

  sync-hub:
    runs-on: ubuntu-22.04
    name: Sync to DockerHub
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      # build
      - name: build
        shell: pwsh
        working-directory: ./build
        run: ./build-sync.ps1  -TargetNamespace hyx1229

  sync-aliyun:
    runs-on: ubuntu-22.04
    name: Sync to Aliyun
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # login docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{env.ALIYUN_DOCKERHUB}}
          username: ${{env.ALIYUN_DOCKERHUB_USERNAME}}
          password: ${{env.ALIYUN_DOCKERHUB_TOKEN}}

      # build
      - name: build
        shell: pwsh
        working-directory: ./build
        run: ./build-sync.ps1 -TargetRegistry $env:ALIYUN_DOCKERHUB
